- platform: template
  sensors:
    # Давление в кабинете
    pressure_workroom:
      friendly_name: "Давление в кабинете"
      device_class: pressure
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_workroom_1_pressure', 'pressure') }}
    # Давление на кухне
    pressure_kitchen:
      friendly_name: "Давление на кухне"
      device_class: pressure
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_kitchen_1_pressure', 'pressure') }}
    # Давление в ванной
    pressure_bathroom:
      friendly_name: "Давление в ванной"
      device_class: pressure
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_bathroom_1_pressure', 'pressure') }}
    # Давление в спальне
    pressure_bedroom:
      friendly_name: "Давление в спальне"
      device_class: pressure
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_bedroom_1_pressure', 'pressure') }}
