- platform: template
  sensors:
    # Температура в кабинете
    temperature_workroom:
      friendly_name: "Температура в кабинете"
      device_class: temperature
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_workroom_1_temperature', 'temperature') }}
    # Температура на кухне
    temperature_kitchen:
      friendly_name: "Температура на кухне"
      device_class: temperature
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_kitchen_1_temperature', 'temperature') }}
    # Температура в ванной
    temperature_bathroom:
      friendly_name: "Температура в ванной"
      device_class: temperature
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_bathroom_1_temperature', 'temperature') }}
    # Температура в спальне
    temperature_bedroom:
      friendly_name: "Температура в спальне"
      device_class: temperature
      value_template: >-
        {{ state_attr('sensor.aqara_temperature_bedroom_1_temperature', 'temperature') }}
    # Температура дома
    temperature_home:
      friendly_name: "Температура дома"
      device_class: temperature
      value_template: >-
        {{ ((state_attr('sensor.aqara_temperature_bedroom_1_temperature', 'temperature') + state_attr('sensor.aqara_temperature_kitchen_1_temperature', 'temperature') + state_attr('sensor.aqara_temperature_workroom_1_temperature', 'temperature')) / 3) | float | round(2) }}
