blueprint:
  name: Включение по датчику движения
  description: Включает свитч по датчику движения и выключает через заданное время
  domain: automation
  input:
    motion_entity:
      name: Датчик движения
      description: При движении включает свитч
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    switch_entity:
      name: Выключатель
      description: Конечное устройство для переключения
      selector:
        entity:
          domain: switch

    turn_off_wait:
      name: Таймер выключения
      description: Выключиться после сработанного датчика движения. Если значение не задано - включаться по движению не будет
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    turn_off_no_motion:
      name: Таймер простоя
      description: Выключить без сработанного датчика движения
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

variables:
  turn_off_wait: !input "turn_off_wait"

trigger:
  - platform: state
    entity_id: !input motion_entity
  - platform: state
    entity_id: !input switch_entity
    from: "off"
    to: "on"

action:
  choose:
    # 1. Включился без датчика движения
    - conditions:
        - condition: state
          entity_id: !input motion_entity
          state: "off"
        - condition: state
          entity_id: !input switch_entity
          state: "on"
      sequence:
        - delay: !input turn_off_no_motion
        - condition: state
          entity_id: !input motion_entity
          state: "off"
        - service: homeassistant.turn_off
          entity_id: !input switch_entity

    # 2. Включился от датчика движения
    - conditions:
        - condition: state
          entity_id: !input motion_entity
          state: "on"
        - condition: state
          entity_id: !input switch_entity
          state: "off"
        - condition: template
          value_template: "{{ (turn_off_wait != none) and (turn_off_wait | int > 0) }}"
      sequence:
        - service: homeassistant.turn_on
          entity_id: !input switch_entity
        - wait_for_trigger:
            - platform: state
              entity_id: !input motion_entity
              from: "on"
              to: "off"
        - delay: !input turn_off_wait
        - service: homeassistant.turn_off
          entity_id: !input switch_entity

    # 3. Включился от датчика движения, но без установленного выключения
    - conditions:
        - condition: state
          entity_id: !input motion_entity
          state: "on"
        - condition: state
          entity_id: !input switch_entity
          state: "on"
        - condition: template
          value_template: "{{ (turn_off_wait == none) or (turn_off_wait | int == 0) }}"
      sequence:
        - wait_for_trigger:
            - platform: state
              entity_id: !input motion_entity
              from: "on"
              to: "off"
        - delay: !input turn_off_no_motion
        - service: homeassistant.turn_off
          entity_id: !input switch_entity
